[AppConfig]
Host = "127.0.0.1"
Port = ":8040"

[AppTimeout]
Server = 60
Read = 60
Write = 60
Idle = 10

[AppDatabase]
Host = "localhost"
User = "postgres"
Password = "postgres"
Name = "goreststarterdb"
Port = "5432"

[AppRoot]
Username = "admin"
Password = "password"

[JWTConfig]
JWTSecretKey = "veryverysecretkey"
TokenExpiry = 60  #Expiry in minutes

[RedisConfig]
Host = "127.0.0.1"
Port = "6379"
Password = ""
DB = 0