[AppConfig]
Host = "127.0.0.1"
Port = ":8040"

[AppTimeout]
Server = 30
Read = 15
Write = 10
Idle = 5

[AppDatabase]
Host = "localhost"
User = "postgres"
Password = "postgres"
Name = "financetrackerdb"
Port = "5432"

[AppRoot]
Username = "admin"
Password = "admin"