// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"finance-tracker/internal/data"
	"finance-tracker/internal/mods/auth/api"
	"finance-tracker/internal/mods/auth/biz"
	"finance-tracker/internal/mods/auth/dal"
	"finance-tracker/pkg/config"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeDependencies() (*Handlers, error) {
	app := ProvideConfig()
	db := ProvideDatabase(app)
	user := &dal.User{
		DB: db,
	}
	bizUser := biz.User{
		UserDAL: user,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	handlers := &Handlers{
		UserApi: apiUser,
	}
	return handlers, nil
}

// wire.go:

type Handlers struct {
	UserApi *api.User
}

// ProvideConfig menyediakan konfigurasi aplikasi.
func ProvideConfig() config.App {
	return config.LoadConfigs()
}

// ProvideDatabase menyediakan koneksi database.
func ProvideDatabase(cfg config.App) *gorm.DB {
	dsn := "host=" + cfg.DatabaseConfig.Host +
		" user=" + cfg.DatabaseConfig.User +
		" password=" + cfg.DatabaseConfig.Password +
		" dbname=" + cfg.DatabaseConfig.Name +
		" port=" + cfg.DatabaseConfig.Port +
		" sslmode=disable"

	return data.InitDatabase(dsn)
}
