openapi: "3.0.0"
info:
  title: "App1 API"
  version: "1.0.0"
paths:
  /login:
    post:
      summary: "Login to the system"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "../internal/auth/schema/login.go"
      responses:
        "200":
          description: "Successful login"
